objects/RateConversionHistory__c/RateConversionHistory__c.object-meta.xml
<CustomObject>
    <label>RateConversionHistory</label>
    <nameField>
        <displayFormat>HIST-{0000}</displayFormat>
        <label>RateConversionHistory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RateConversionHistories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RateConversionHistory__c/fields/Amount_to_convert__c.field-meta.xml
<CustomField>
    <fullName>Amount_to_convert__c</fullName>
    <label>Amount to convert</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/RateConversionHistory__c/fields/Converted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Converted_Amount__c</fullName>
    <label>Converted Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/RateConversionHistory__c/fields/Converted_Currency__c.field-meta.xml
<CustomField>
    <fullName>Converted_Currency__c</fullName>
    <label>Converted Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/RateConversionHistory__c/fields/Currency_to_Convert__c.field-meta.xml
<CustomField>
    <fullName>Currency_to_Convert__c</fullName>
    <label>Currency to Convert</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/RateConverterCtrl.cls
public class RateConverterCtrl {
    
    @AuraEnabled
    public static List< RateConversionHistory__c > getRateHistories(){
        return [SELECT Id,Name,Amount_to_convert__c ,Converted_Amount__c, Converted_Currency__c, Currency_to_Convert__c  
                FROM RateConversionHistory__c ORDER BY CreatedDate DESC];
    }
    
    @AuraEnabled
    public static void createRecord(string fromCurrency,string toCurrency,Decimal fromAmt,Decimal toAmt){
        INSERT new RateConversionHistory__c(Amount_to_convert__c=fromAmt,
                                            Converted_Currency__c=fromCurrency,
                                            Currency_to_Convert__c=toCurrency,
                                            Converted_Amount__c=toAmt);
    }
}